buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:${agpVersion}"
    }
}

allprojects {
    apply plugin: "eclipse"

    version = "1.0"

    ext {
        appName = "re-wilder"
    }

    repositories {
        google()
        mavenCentral()
    }
}